front: upgrade node to v23
A newer node version is required [1] to make require() work with
modules. This is necessary for a nivo upgrade, otherwise CI fails
with:

     FAIL  src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts [ src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts ]
    Error: require() of ES Module /app/node_modules/d3-interpolate/src/index.js from /app/node_modules/@nivo/core/dist/nivo-core.cjs.js not supported.
    Instead change the require of index.js in /app/node_modules/@nivo/core/dist/nivo-core.cjs.js to a dynamic import() which is available in all CommonJS modules.
     ❯ Object.<anonymous> node_modules/@nivo/core/dist/nivo-core.cjs.js:1:164

[1]: https://github.com/plouc/nivo/issues/2310#issuecomment-2495916321

Signed-off-by: Simon Ser <contact@emersion.fr>